"""create_initial_tables

Revision ID: 30257fbe1e49
Revises: 
Create Date: 2025-12-27 17:23:41.304593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30257fbe1e49'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Enable pg_trgm extension for GIN indexes
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')

    op.create_table('dvf_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('source_file_hash', sa.String(length=64), nullable=False),
    sa.Column('data_year', sa.Integer(), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('inserted_records', sa.Integer(), nullable=True),
    sa.Column('updated_records', sa.Integer(), nullable=True),
    sa.Column('skipped_records', sa.Integer(), nullable=True),
    sa.Column('error_records', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_file_hash')
    )
    op.create_index('idx_dvf_imports_status', 'dvf_imports', ['status'], unique=False)
    op.create_index('idx_dvf_imports_year_status', 'dvf_imports', ['data_year', 'status'], unique=False)
    op.create_index(op.f('ix_dvf_imports_batch_id'), 'dvf_imports', ['batch_id'], unique=True)
    op.create_index(op.f('ix_dvf_imports_data_year'), 'dvf_imports', ['data_year'], unique=False)
    op.create_index(op.f('ix_dvf_imports_id'), 'dvf_imports', ['id'], unique=False)
    op.create_table('dvf_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('property_type', sa.String(), nullable=True),
    sa.Column('surface_area', sa.Float(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('land_surface', sa.Float(), nullable=True),
    sa.Column('price_per_sqm', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('data_year', sa.Integer(), nullable=True),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('source_file_hash', sa.String(length=64), nullable=True),
    sa.Column('import_batch_id', sa.String(length=36), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('transaction_group_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dvf_address_gin', 'dvf_records', ['address'], unique=False, postgresql_using='gin', postgresql_ops={'address': 'gin_trgm_ops'})
    op.create_index('idx_dvf_date_postal_type', 'dvf_records', ['sale_date', 'postal_code', 'property_type'], unique=False)
    op.create_index('idx_dvf_postal_type_address', 'dvf_records', ['postal_code', 'property_type', 'address'], unique=False)
    op.create_index('idx_dvf_postal_type_surface', 'dvf_records', ['postal_code', 'property_type', 'surface_area'], unique=False)
    op.create_index('idx_dvf_price_per_sqm', 'dvf_records', ['price_per_sqm'], unique=False, postgresql_where='price_per_sqm > 0')
    op.create_index('idx_dvf_unique_sale', 'dvf_records', ['sale_date', 'sale_price', 'address', 'postal_code', 'surface_area'], unique=True)
    op.create_index(op.f('ix_dvf_records_city'), 'dvf_records', ['city'], unique=False)
    op.create_index(op.f('ix_dvf_records_data_year'), 'dvf_records', ['data_year'], unique=False)
    op.create_index(op.f('ix_dvf_records_department'), 'dvf_records', ['department'], unique=False)
    op.create_index(op.f('ix_dvf_records_id'), 'dvf_records', ['id'], unique=False)
    op.create_index(op.f('ix_dvf_records_import_batch_id'), 'dvf_records', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_dvf_records_postal_code'), 'dvf_records', ['postal_code'], unique=False)
    op.create_index(op.f('ix_dvf_records_sale_date'), 'dvf_records', ['sale_date'], unique=False)
    op.create_index(op.f('ix_dvf_records_transaction_group_id'), 'dvf_records', ['transaction_group_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('asking_price', sa.Float(), nullable=True),
    sa.Column('surface_area', sa.Float(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('property_type', sa.String(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('building_year', sa.Integer(), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('price_per_sqm', sa.Float(), nullable=True),
    sa.Column('market_comparison_score', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('investment_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('value_score', sa.Float(), nullable=True),
    sa.Column('overall_recommendation', sa.String(), nullable=True),
    sa.Column('estimated_fair_price', sa.Float(), nullable=True),
    sa.Column('price_deviation_percent', sa.Float(), nullable=True),
    sa.Column('comparable_properties_count', sa.Integer(), nullable=True),
    sa.Column('annual_charges', sa.Float(), nullable=True),
    sa.Column('annual_taxe_fonciere', sa.Float(), nullable=True),
    sa.Column('upcoming_works_cost', sa.Float(), nullable=True),
    sa.Column('estimated_annual_cost', sa.Float(), nullable=True),
    sa.Column('has_amiante', sa.Boolean(), nullable=True),
    sa.Column('has_plomb', sa.Boolean(), nullable=True),
    sa.Column('dpe_rating', sa.String(), nullable=True),
    sa.Column('ges_rating', sa.String(), nullable=True),
    sa.Column('copropriete_health_score', sa.Float(), nullable=True),
    sa.Column('pending_works', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_id'), 'analyses', ['id'], unique=False)
    op.create_table('document_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_findings', sa.JSON(), nullable=True),
    sa.Column('total_estimated_annual_cost', sa.Float(), nullable=True),
    sa.Column('total_one_time_costs', sa.Float(), nullable=True),
    sa.Column('cost_breakdown', sa.JSON(), nullable=True),
    sa.Column('copropriete_insights', sa.JSON(), nullable=True),
    sa.Column('diagnostic_issues', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_document_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_summaries_id'), 'document_summaries', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('document_category', sa.String(), nullable=True),
    sa.Column('document_subcategory', sa.String(), nullable=True),
    sa.Column('document_date', sa.DateTime(), nullable=True),
    sa.Column('is_analyzed', sa.Boolean(), nullable=True),
    sa.Column('analysis_summary', sa.Text(), nullable=True),
    sa.Column('extracted_data', sa.Text(), nullable=True),
    sa.Column('risk_flags', sa.Text(), nullable=True),
    sa.Column('key_insights', sa.JSON(), nullable=True),
    sa.Column('estimated_annual_cost', sa.Float(), nullable=True),
    sa.Column('one_time_costs', sa.JSON(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_document_summaries_id'), table_name='document_summaries')
    op.drop_table('document_summaries')
    op.drop_index(op.f('ix_analyses_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_dvf_records_transaction_group_id'), table_name='dvf_records')
    op.drop_index(op.f('ix_dvf_records_sale_date'), table_name='dvf_records')
    op.drop_index(op.f('ix_dvf_records_postal_code'), table_name='dvf_records')
    op.drop_index(op.f('ix_dvf_records_import_batch_id'), table_name='dvf_records')
    op.drop_index(op.f('ix_dvf_records_id'), table_name='dvf_records')
    op.drop_index(op.f('ix_dvf_records_department'), table_name='dvf_records')
    op.drop_index(op.f('ix_dvf_records_data_year'), table_name='dvf_records')
    op.drop_index(op.f('ix_dvf_records_city'), table_name='dvf_records')
    op.drop_index('idx_dvf_unique_sale', table_name='dvf_records')
    op.drop_index('idx_dvf_price_per_sqm', table_name='dvf_records', postgresql_where='price_per_sqm > 0')
    op.drop_index('idx_dvf_postal_type_surface', table_name='dvf_records')
    op.drop_index('idx_dvf_postal_type_address', table_name='dvf_records')
    op.drop_index('idx_dvf_date_postal_type', table_name='dvf_records')
    op.drop_index('idx_dvf_address_gin', table_name='dvf_records', postgresql_using='gin', postgresql_ops={'address': 'gin_trgm_ops'})
    op.drop_table('dvf_records')
    op.drop_index(op.f('ix_dvf_imports_id'), table_name='dvf_imports')
    op.drop_index(op.f('ix_dvf_imports_data_year'), table_name='dvf_imports')
    op.drop_index(op.f('ix_dvf_imports_batch_id'), table_name='dvf_imports')
    op.drop_index('idx_dvf_imports_year_status', table_name='dvf_imports')
    op.drop_index('idx_dvf_imports_status', table_name='dvf_imports')
    op.drop_table('dvf_imports')
    # ### end Alembic commands ###
