#!/usr/bin/env bash
# =============================================================================
# Setup GCS Bucket for Terraform Remote State
# =============================================================================
#
# This script creates a GCS bucket to store Terraform state remotely,
# enabling team collaboration on infrastructure.
#
# Usage:
#   ./scripts/setup-remote-state.sh <PROJECT_ID> [REGION]
#
# Example:
#   ./scripts/setup-remote-state.sh my-gcp-project europe-west1
#
# What it does:
#   1. Creates a GCS bucket named <PROJECT_ID>-appartagent-tfstate
#   2. Enables object versioning (for state recovery)
#   3. Sets a 90-day lifecycle policy on non-current versions
#   4. Generates a backend.hcl file for terraform init
#
# After running this script:
#   cd infra/terraform
#   terraform init -backend-config=backend.hcl
#
# If migrating from local state:
#   terraform init -backend-config=backend.hcl -migrate-state
#
# =============================================================================

set -euo pipefail

# --- Arguments ---
PROJECT_ID="${1:?Usage: $0 <PROJECT_ID> [REGION]}"
REGION="${2:-europe-west1}"

BUCKET_NAME="${PROJECT_ID}-appartagent-tfstate"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TERRAFORM_DIR="$(dirname "$SCRIPT_DIR")"

echo "============================================="
echo " Terraform Remote State Setup"
echo "============================================="
echo ""
echo "  Project:  ${PROJECT_ID}"
echo "  Region:   ${REGION}"
echo "  Bucket:   gs://${BUCKET_NAME}"
echo ""

# --- Ensure gcloud is configured for the right project ---
CURRENT_PROJECT=$(gcloud config get-value project 2>/dev/null || true)
if [ "$CURRENT_PROJECT" != "$PROJECT_ID" ]; then
  echo "⚠  Current gcloud project is '${CURRENT_PROJECT}', switching to '${PROJECT_ID}'..."
  gcloud config set project "$PROJECT_ID"
fi

# --- Check if bucket already exists ---
if gsutil ls -b "gs://${BUCKET_NAME}" &>/dev/null; then
  echo "✓  Bucket gs://${BUCKET_NAME} already exists."
else
  echo "→  Creating bucket gs://${BUCKET_NAME}..."
  gsutil mb -p "$PROJECT_ID" -l "$REGION" -b on "gs://${BUCKET_NAME}"
  echo "✓  Bucket created."
fi

# --- Enable versioning ---
echo "→  Enabling object versioning..."
gsutil versioning set on "gs://${BUCKET_NAME}"
echo "✓  Versioning enabled."

# --- Set lifecycle policy to clean up old versions after 90 days ---
LIFECYCLE_JSON=$(cat <<'LIFECYCLE'
{
  "rule": [
    {
      "action": { "type": "Delete" },
      "condition": {
        "numNewerVersions": 5,
        "isLive": false
      }
    }
  ]
}
LIFECYCLE
)

echo "→  Setting lifecycle policy (keep last 5 non-current versions)..."
echo "$LIFECYCLE_JSON" | gsutil lifecycle set /dev/stdin "gs://${BUCKET_NAME}"
echo "✓  Lifecycle policy set."

# --- Generate backend.hcl ---
BACKEND_HCL="${TERRAFORM_DIR}/backend.hcl"
cat > "$BACKEND_HCL" <<EOF
# Auto-generated by setup-remote-state.sh
# Bucket: gs://${BUCKET_NAME}
bucket = "${BUCKET_NAME}"
prefix = "terraform/state"
EOF

echo "✓  Generated ${BACKEND_HCL}"

echo ""
echo "============================================="
echo " Setup Complete!"
echo "============================================="
echo ""
echo " Next steps:"
echo ""
echo "   cd infra/terraform"
echo ""
echo "   # If this is a fresh setup (no existing state):"
echo "   terraform init -backend-config=backend.hcl"
echo ""
echo "   # If migrating from local state to remote:"
echo "   terraform init -backend-config=backend.hcl -migrate-state"
echo ""
echo " For other team members (bucket already exists):"
echo "   1. Copy backend.hcl.example to backend.hcl"
echo "   2. Fill in the bucket name: ${BUCKET_NAME}"
echo "   3. Run: terraform init -backend-config=backend.hcl"
echo ""
